version: "3.9"

#volumes:
#  squad_data:
#    name: "/srv/core/portainer-volumes/squad_data_${ENV_NAME:-test}"

services:
  squad-server:
    image: cm2network/squad
    entrypoint: ["/bin/bash", "-c"]
    container_name: "squad-${ENV_NAME:-test}"
    network_mode: "${NETWORK_MODE:-bridge}"
    restart: unless-stopped
    #volumes:
      #- squad_data:/home/steam/squad-dedicated/
      #- "/srv/core/portainer-volumes/squad-data-test:/home/steam/squad-dedicated/"
    environment:
      - HULTIHOME=${SERVER_IP}
      - PORT=${SERVER_PORT:-7787}
      - beaconport=${BEACON_PORT:-15000}
      - QUERYPORT=${QUERY_PORT:-27165}
      - RCONPORT=${RCON_PORT:-21114}
      - FIXEDMAXPLAYERS=${MAX_PLAYERS:-100}
      - SERVER_NAME=${SERVER_NAME:-Default Squad Server}
      - MODS=${MODS}
      - STEAM_BETA_BRANCH=${STEAM_BETA_BRANCH:-}
      - STEAMCMDDIR=${STEAMCMDDIR:-/home/steam/steamcmd}
      - STEAMAPPDIR=${STEAMAPPDIR:-/home/steam/squad-dedicated}
      - STEAM_BETA_APP=${STEAM_BETA_APP:-403240}
      - STEAM_BETA_PASSWORD=${STEAM_BETA_PASSWORD:-}
      - STEAMAPPID=${STEAMAPPID:-403240}
      - MODPATH=${MODPATH:-/home/steam/squad-dedicated/SquadGame/Plugins/Mods}
      - WORKSHOPID=${WORKSHOPID:-403240}
      - FIXEDMAXTICKRATE=${FIXEDMAXTICKRATE:-50}
      - RANDOM=${RANDOM:-}
    ports:
      - "${SERVER_IP}:${SERVER_PORT:-7787}:${SERVER_PORT:-7787}/tcp"
      - "${SERVER_IP}:${SERVER_PORT:-7787}:${SERVER_PORT:-7787}/udp"
      - "${SERVER_IP}:${SERVER_PORT_ADDITIONAL:-7788}:${SERVER_PORT_ADDITIONAL:-7788}/tcp"
      - "${SERVER_IP}:${SERVER_PORT_ADDITIONAL:-7788}:${SERVER_PORT_ADDITIONAL:-7788}/udp"
      - "${SERVER_IP}:${BEACON_PORT:-15000}:${BEACON_PORT:-15000}/tcp"
      - "${SERVER_IP}:${BEACON_PORT:-15000}:${BEACON_PORT:-15000}/udp"
      - "${SERVER_IP}:${QUERY_PORT:-27165}:${QUERY_PORT:-27165}/tcp"
      - "${SERVER_IP}:${QUERY_PORT:-27165}:${QUERY_PORT:-27165}/udp"
      - "${SERVER_IP}:${QUERY_PORT_ADDITIONAL:-27166}:${QUERY_PORT_ADDITIONAL:-27166}/tcp"
      - "${SERVER_IP}:${QUERY_PORT_ADDITIONAL:-27166}:${QUERY_PORT_ADDITIONAL:-27166}/udp"
      - "${SERVER_IP}:${RCON_PORT:-21114}:${RCON_PORT:-21114}/tcp"
      - "${SERVER_IP}:${RCON_PORT:-21114}:${RCON_PORT:-21114}/udp"
    command:
    - |
      #set -e
      if [ -n "$${STEAM_BETA_BRANCH}" ]
      then
        echo "Loading Steam Beta Branch"
        bash "$${STEAMCMDDIR}/steamcmd.sh" +force_install_dir "$${STEAMAPPDIR}" \
          +login anonymous \
          +app_update "$${STEAM_BETA_APP}" \
          -beta "$${STEAM_BETA_BRANCH}" \
          -betapassword "$${STEAM_BETA_PASSWORD}" \
          +quit
      else
        echo "Loading Steam Release Branch"
        bash "$${STEAMCMDDIR}/steamcmd.sh" +force_install_dir "$${STEAMAPPDIR}" \
          +login anonymous \
          +app_update "$${STEAMAPPID}" \
          +quit
      fi
      # Change rcon port on first launch, because the default config overwrites the commandline parameter (you can comment this out if it has done it's purpose)
      echo "Change rcon port on first launch"
      sed -i -e 's/Port=21114/'"Port=$${RCONPORT}"'/g' "$${STEAMAPPDIR}/SquadGame/ServerConfig/Rcon.cfg"
      echo "Clearing Mods..."
      # Clear all workshop mods:
      # find all folders / files in mods folder which are numeric only;
      # remove the workshop mods
      find "$${MODPATH}"/* -maxdepth 0 -regextype posix-egrep -regex ".*/[[:digit:]]+" | xargs -0 -d"\n" rm -R 2>/dev/null
      # Install mods (if defined)
      declare -a MODS="$${MODS}"
      if (( $${#MODS[@]} ))
      then
        echo "Installing Mods..."
        for MODID in "$${MODS[@]}"; do
          echo "> Install mod '$${MODID}'"
          "$${STEAMCMDDIR}/steamcmd.sh" +force_install_dir "$${STEAMAPPDIR}" +login anonymous +workshop_download_item "$${WORKSHOPID}" "$${MODID}" +quit

          echo -e "\n> Link mod content '$${MODID}'"
          ln -s "$${STEAMAPPDIR}/steamapps/workshop/content/$${WORKSHOPID}/$${MODID}" "$${MODPATH}/$${MODID}"
        done
      fi
      exec "$${STEAMAPPDIR}/SquadGameServer.sh" \
        MULTIHOME="$${MULTIHOME}" \
        Port="$${PORT}" \
        QueryPort="$${QUERYPORT}" \
        RCONPORT="$${RCONPORT}" \
        FIXEDMAXPLAYERS="$${FIXEDMAXPLAYERS}" \
        FIXEDMAXTICKRATE="$${FIXEDMAXTICKRATE}" \
        RANDOM="$${RANDOM}" \
        -beaconport="$${beaconport}" \
        -log
